---
kind: pipeline
type: docker
name: source-code-analysis-snyk
      
steps:
  - name: snyk-pr
    pull: if-not-exists
    image: snyk/snyk:linux
#https://github.com/snyk/snyk-images    
    volumes:
      - name: cache
        path: ~/.sonar
    environment:
        snyk_username:
          from_secret: snyk_username
        snyk_password:
          from_secret: snyk_password
        SNYK_TOKEN:
          from_secret: snyk_token
# b2b35c8-a1b4-4a83-bb02-31adda7ed8c2       
    commands:
      - snyk auth b2b35c8-a1b4-4a83-bb02-31adda7ed8c2   
      - snyk test -d 
    when:
      branch: 
        - main
      event: 
        include:
          - pull_request
      ref:
        - refs/heads/main
        - refs/pull/**
#    depends_on:
#      - source-code-analysis-pr-init
